
from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import shutil
import os
import uuid
from .core.engine import ArgusEngine
from .core.telemetry import Telemetry

# Initialize App
app = FastAPI(title="Project ARGUS API", version="1.0.0")

# CORS (Allow Frontend)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://localhost:3001", "http://127.0.0.1:3000", "http://127.0.0.1:3001"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

logger = Telemetry.get_logger("API")

# Storage for demo
UPLOAD_DIR = "evidence_vault"
os.makedirs(UPLOAD_DIR, exist_ok=True)

# In-memory session store (for demo purposes)
sessions = {}

@app.post("/api/case/new")
async def create_case():
    case_id = str(uuid.uuid4())
    engine = ArgusEngine(case_id)
    sessions[case_id] = engine
    logger.info(f"Created new case: {case_id}")
    return {"case_id": case_id, "status": "initialized"}

@app.post("/api/evidence/upload/{case_id}")
async def upload_evidence(case_id: str, file: UploadFile = File(...)):
    if case_id not in sessions:
        raise HTTPException(status_code=404, detail="Case not found")
        
    engine = sessions[case_id]
    
    # Save file securely
    safe_filename = f"{uuid.uuid4()}_{file.filename}"
    file_location = os.path.join(UPLOAD_DIR, safe_filename)
    
    with open(file_location, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)
        
    # Ingest
    block_id = engine.ingest_evidence(file_location)
    
    return {"status": "uploaded", "file_path": file_location, "block_id": block_id}

@app.get("/api/evidence/{case_id}")
async def list_evidence(case_id: str):
    if case_id not in sessions:
        # For demo persistence: if session lost (restart), re-create it scanning the dir
        # This makes it robust to server restarts!
        sessions[case_id] = ArgusEngine(case_id)
        # Scan dir? implementation detail. For now just check folder.
    
    # Simple directory scan for demo
    files = []
    if os.path.exists(UPLOAD_DIR):
        for f in os.listdir(UPLOAD_DIR):
            path = os.path.join(UPLOAD_DIR, f)
            stat = os.stat(path)
            files.append({
                "name": f,
                "size": f"{stat.st_size / 1024:.2f} KB",
                "type": f.split('.')[-1].upper(),
                "status": "Secured (SHA3)",
                "progress": 100
            })
    return {"files": files}

@app.delete("/api/evidence/{case_id}/{filename}")
async def delete_evidence(case_id: str, filename: str):
    file_path = os.path.join(UPLOAD_DIR, filename)
    if os.path.exists(file_path):
        os.remove(file_path)
        return {"status": "deleted"}
    raise HTTPException(status_code=404, detail="File not found")

@app.delete("/api/evidence/{case_id}/clear")
async def clear_all_evidence(case_id: str):
    """Clear all evidence files from the vault."""
    if not os.path.exists(UPLOAD_DIR):
        return {"status": "cleared", "count": 0}
    
    count = 0
    for f in os.listdir(UPLOAD_DIR):
        file_path = os.path.join(UPLOAD_DIR, f)
        if os.path.isfile(file_path):
            os.remove(file_path)
            count += 1
    
    logger.info(f"Cleared {count} files from evidence vault for case {case_id}")
    return {"status": "cleared", "count": count}

from fastapi.responses import FileResponse

@app.get("/api/report/{case_id}/download")
async def download_report(case_id: str):
    """Download the generated PDF report."""
    
    # 1. Look for Enhanced Report FIRST (Generated by POST request)
    enhanced_path = f"Report_Enhanced_{case_id}.pdf"
    if os.path.exists(enhanced_path):
        filename = f"Forensic_Report_{case_id}.pdf"
        return FileResponse(enhanced_path, media_type='application/pdf', filename=filename)

    # 2. Fallback: Initialize engine if needed
    if case_id not in sessions:
        sessions[case_id] = ArgusEngine(case_id)
    
    engine = sessions[case_id]
    
    # 3. Regenerate fallback (Basic shell)
    path = engine.generate_final_report({"summary": "Full case analysis completed."})
    
    if os.path.exists(path):
        filename = f"Forensic_Report_{case_id}.pdf"
        return FileResponse(path, media_type='application/pdf', filename=filename)
    
    raise HTTPException(status_code=404, detail="Report generation failed")

@app.post("/api/analyze/{case_id}")
async def analyze_evidence(case_id: str, file_path: str, type: str = "image"):
    if case_id not in sessions:
        raise HTTPException(status_code=404, detail="Case not found")
    
    engine = sessions[case_id]
    results = engine.analyze_artifact(file_path, artifact_type=type)
    
    return results

@app.get("/api/report/{case_id}")
async def generate_report(case_id: str):
    if case_id not in sessions:
        raise HTTPException(status_code=404, detail="Case not found")

    # For demo, we just pass empty result dict if not tracked in engine state
    # Ideally engine would track state.
    engine = sessions[case_id]
    
    # In a real app, we'd aggregate all results. 
    # Here we just generate a report with whatever last analysis was or placeholders.
    path = engine.generate_final_report({"summary": "Full case analysis completed."})
    
    return {"status": "generated", "report_path": path}

# === NLP Analysis Endpoint ===
from pydantic import BaseModel
import spacy
from langdetect import detect, detect_langs

# Language name mapping
LANGUAGE_NAMES = {
    'en': 'English', 'es': 'Spanish', 'fr': 'French', 'de': 'German',
    'it': 'Italian', 'pt': 'Portuguese', 'nl': 'Dutch', 'ru': 'Russian',
    'zh-cn': 'Chinese (Simplified)', 'zh-tw': 'Chinese (Traditional)',
    'ja': 'Japanese', 'ko': 'Korean', 'ar': 'Arabic', 'hi': 'Hindi',
    'bn': 'Bengali', 'pa': 'Punjabi', 'ta': 'Tamil', 'te': 'Telugu',
    'mr': 'Marathi', 'gu': 'Gujarati', 'tr': 'Turkish', 'pl': 'Polish',
    'uk': 'Ukrainian', 'vi': 'Vietnamese', 'th': 'Thai', 'id': 'Indonesian',
    'sv': 'Swedish', 'no': 'Norwegian', 'da': 'Danish', 'fi': 'Finnish',
    'he': 'Hebrew', 'fa': 'Persian', 'cs': 'Czech', 'ro': 'Romanian',
    'hu': 'Hungarian', 'el': 'Greek', 'bg': 'Bulgarian', 'sk': 'Slovak',
    'sl': 'Slovenian', 'hr': 'Croatian', 'sr': 'Serbian', 'lt': 'Lithuanian',
    'lv': 'Latvian', 'et': 'Estonian', 'tl': 'Tagalog', 'ms': 'Malay',
    'sw': 'Swahili', 'af': 'Afrikaans', 'ca': 'Catalan', 'cy': 'Welsh'
}

# Load multilingual spaCy model
try:
    nlp_multi = spacy.load("xx_ent_wiki_sm")
    logger.info("spaCy multilingual NLP model loaded successfully")
except Exception as e:
    logger.warning(f"Multilingual model not found, trying English: {e}")
    try:
        nlp_multi = spacy.load("en_core_web_sm")
        logger.info("Fallback to English spaCy model")
    except:
        nlp_multi = None
        logger.error("No spaCy model available")

class NLPRequest(BaseModel):
    case_id: str
    text: str

@app.post("/api/nlp/analyze")
async def analyze_nlp(request: NLPRequest):
    text = request.text
    text_lower = text.lower()
    
    # === Language Detection ===
    detected_lang = "unknown"
    detected_lang_name = "Unknown"
    lang_confidence = 0.0
    
    try:
        lang_results = detect_langs(text)
        if lang_results:
            detected_lang = str(lang_results[0].lang)
            lang_confidence = lang_results[0].prob
            detected_lang_name = LANGUAGE_NAMES.get(detected_lang, detected_lang.upper())
    except Exception as e:
        logger.warning(f"Language detection failed: {e}")
    
    # === Named Entity Recognition ===
    entities = {
        "persons": [],
        "locations": [],
        "organizations": [],
        "dates": [],
        "money": [],
        "misc": []
    }
    
    if nlp_multi:
        doc = nlp_multi(text)
        for ent in doc.ents:
            entity_info = {"text": ent.text, "label": ent.label_, "start": ent.start_char, "end": ent.end_char}
            
            # Multilingual model uses PER for persons, LOC for locations, ORG for organizations
            if ent.label_ in ["PERSON", "PER"]:
                entities["persons"].append(entity_info)
            elif ent.label_ in ["GPE", "LOC", "FAC"]:
                entities["locations"].append(entity_info)
            elif ent.label_ in ["ORG", "NORP"]:
                entities["organizations"].append(entity_info)
            elif ent.label_ in ["DATE", "TIME", "EVENT"]:
                entities["dates"].append(entity_info)
            elif ent.label_ in ["MONEY", "QUANTITY", "CARDINAL"]:
                entities["money"].append(entity_info)
            else:
                entities["misc"].append(entity_info)
    
    # === Threat & Sentiment Analysis ===
    aggression_keywords = ['hate', 'kill', 'destroy', 'revolution', 'attack', 'fight', 'war', 'enemy', 'bomb', 'weapon', 'threat']
    negative_keywords = ['angry', 'bad', 'terrible', 'wrong', 'corrupt', 'evil', 'lie', 'fake', 'danger', 'fear']
    
    aggression_matches = [word for word in aggression_keywords if word in text_lower]
    aggression_score = len(aggression_matches) / len(aggression_keywords) * 10
    sentiment = "Negative" if any(word in text_lower for word in negative_keywords) else "Neutral"
    
    radicalization = "HIGH" if aggression_score > 3 else "MEDIUM" if aggression_score > 1 else "LOW"
    
    # === Stylometry Analysis ===
    words = text.split()
    word_count = len(words)
    avg_word_len = sum(len(w) for w in words) / max(word_count, 1)
    sentences = text.count('.') + text.count('!') + text.count('?')
    avg_sentence_len = word_count / max(sentences, 1)
    
    # Vocabulary richness (unique words / total words)
    unique_words = len(set(w.lower() for w in words))
    vocab_richness = unique_words / max(word_count, 1)
    
    # === Authorship Mock (based on stylometry) ===
    author_match = min(95, 65 + (avg_word_len * 2) + (vocab_richness * 20))
    
    return {
        "language": {
            "code": detected_lang,
            "name": detected_lang_name,
            "confidence": round(lang_confidence * 100, 1)
        },
        "entities": entities,
        "entity_summary": {
            "total_persons": len(entities["persons"]),
            "total_locations": len(entities["locations"]),
            "total_organizations": len(entities["organizations"]),
            "total_dates": len(entities["dates"])
        },
        "authorship": [
            {"name": "Suspect_Alpha", "match": round(author_match, 1)},
            {"name": "Unknown_User", "match": round(max(15, author_match - 50), 1)}
        ],
        "radicalization": {
            "level": radicalization,
            "percentage": min(int(aggression_score * 10 + 20), 95),
            "sentiment": sentiment,
            "aggression": round(min(aggression_score + 2, 10), 1),
            "keywords_found": aggression_matches
        },
        "stylometry": {
            "word_count": word_count,
            "avg_word_length": round(avg_word_len, 2),
            "avg_sentence_length": round(avg_sentence_len, 2),
            "vocabulary_richness": round(vocab_richness * 100, 1),
            "complexity": "High" if avg_word_len > 6 else "Medium" if avg_word_len > 4 else "Low"
        }
    }

# === Authorship Analysis APIs (PRD Module 2) ===
from .nlp.stylometry_engine import EnhancedStylometry

# In-memory suspect profile storage (for demo)
suspect_profiles = {}
enhanced_stylometry = EnhancedStylometry()

class AuthorshipTrainRequest(BaseModel):
    suspect_id: str
    writing_samples: list[str]

class AuthorshipCompareRequest(BaseModel):
    unknown_text: str
    suspect_ids: list[str] = []  # Empty = compare against all

@app.post("/api/nlp/train-profile")
async def train_author_profile(request: AuthorshipTrainRequest):
    """Train a stylometric profile for a suspect using their writing samples."""
    if not request.writing_samples:
        raise HTTPException(status_code=400, detail="At least one writing sample required")
    
    # Combine all samples and extract features
    combined_text = " ".join(request.writing_samples)
    features = enhanced_stylometry.extract_all_features(combined_text)
    patterns = enhanced_stylometry.highlight_patterns(combined_text)
    
    suspect_profiles[request.suspect_id] = {
        "features": features,
        "patterns": patterns,
        "sample_count": len(request.writing_samples),
        "total_words": len(combined_text.split())
    }
    
    logger.info(f"Trained profile for suspect: {request.suspect_id}")
    
    return {
        "status": "trained",
        "suspect_id": request.suspect_id,
        "sample_count": len(request.writing_samples),
        "feature_summary": {
            "char_ngrams_extracted": len(features.get("char_3grams", {})),
            "avg_sentence_length": round(features.get("sentence_metrics", {}).get("avg_sentence_length", 0), 2),
            "unique_markers": patterns.get("unique_markers", [])
        }
    }

@app.post("/api/nlp/compare-authors")
async def compare_authorship(request: AuthorshipCompareRequest):
    """Compare unknown text against trained suspect profiles."""
    if not request.unknown_text:
        raise HTTPException(status_code=400, detail="Unknown text required")
    
    if not suspect_profiles:
        raise HTTPException(status_code=400, detail="No suspect profiles trained. Use /api/nlp/train-profile first.")
    
    # Extract features from unknown text
    unknown_features = enhanced_stylometry.extract_all_features(request.unknown_text)
    unknown_patterns = enhanced_stylometry.highlight_patterns(request.unknown_text)
    
    # Compare against suspects
    targets = request.suspect_ids if request.suspect_ids else list(suspect_profiles.keys())
    
    matches = []
    for suspect_id in targets:
        if suspect_id not in suspect_profiles:
            continue
        
        profile = suspect_profiles[suspect_id]
        similarity = enhanced_stylometry.compute_similarity(unknown_features, profile["features"])
        
        matches.append({
            "suspect_id": suspect_id,
            "similarity_percentage": similarity,
            "confidence": "HIGH" if similarity > 70 else "MEDIUM" if similarity > 50 else "LOW",
            "sample_count": profile.get("sample_count", 0)
        })
    
    # Sort by similarity (highest first)
    matches.sort(key=lambda x: x["similarity_percentage"], reverse=True)
    
    return {
        "unknown_text_preview": request.unknown_text[:100] + "..." if len(request.unknown_text) > 100 else request.unknown_text,
        "patterns_found": unknown_patterns,
        "ranked_matches": matches,
        "top_match": matches[0] if matches else None,
        "total_suspects_compared": len(matches)
    }

@app.get("/api/nlp/profiles")
async def list_trained_profiles():
    """List all trained suspect profiles."""
    profiles_summary = []
    for suspect_id, data in suspect_profiles.items():
        profiles_summary.append({
            "suspect_id": suspect_id,
            "sample_count": data.get("sample_count", 0),
            "total_words": data.get("total_words", 0),
            "unique_markers": data.get("patterns", {}).get("unique_markers", [])
        })
    
    return {"profiles": profiles_summary, "total_count": len(profiles_summary)}


class VisionRequest(BaseModel):
    case_id: str
    file_path: str

@app.post("/api/vision/analyze")
async def analyze_vision(request: VisionRequest):
    from .vision.gan_detector import GANDetector
    
    detector = GANDetector()
    results = detector.analyze_image(request.file_path)
    
    return results

# === ELA & Manipulation Detection APIs (PRD Module 4) ===
from .vision.ela_analyzer import ELAAnalyzer, ManipulationDetector

ela_analyzer = ELAAnalyzer()
manipulation_detector = ManipulationDetector()

class ELARequest(BaseModel):
    file_path: str
    save_heatmap: bool = True

@app.post("/api/vision/ela")
async def analyze_ela(request: ELARequest):
    """Perform Error Level Analysis on an image."""
    if not os.path.exists(request.file_path):
        raise HTTPException(status_code=404, detail="Image file not found")
    
    result = ela_analyzer.full_analysis(request.file_path, request.save_heatmap)
    
    if "error" in result:
        raise HTTPException(status_code=500, detail=result["error"])
    
    return {
        "status": "analyzed",
        "metrics": result.get("metrics"),
        "risk": result.get("risk"),
        "heatmap_path": result.get("heatmap_path"),
        "image_size": result.get("image_size")
    }

@app.post("/api/vision/manipulation")
async def detect_manipulation(request: ELARequest):
    """Full manipulation detection: ELA + DCT + Copy-Move."""
    if not os.path.exists(request.file_path):
        raise HTTPException(status_code=404, detail="Image file not found")
    
    result = manipulation_detector.detect(request.file_path)
    
    return result

@app.get("/api/vision/ela/heatmap/{filename}")
async def get_ela_heatmap(filename: str):
    """Get ELA heatmap image for a file."""
    # Look for heatmap in evidence vault
    heatmap_path = os.path.join(UPLOAD_DIR, f"{os.path.splitext(filename)[0]}_ela_heatmap.png")
    
    if os.path.exists(heatmap_path):
        return FileResponse(heatmap_path, media_type="image/png")
    
    # Try to generate on-the-fly
    source_path = os.path.join(UPLOAD_DIR, filename)
    if os.path.exists(source_path):
        generated_path = ela_analyzer.generate_heatmap(source_path, heatmap_path)
        if generated_path and os.path.exists(generated_path):
            return FileResponse(generated_path, media_type="image/png")
    
    raise HTTPException(status_code=404, detail="Heatmap not found")


from .graph.hidden_nexus import EnhancedGraphAnalyzer

# Global graph instance for demo
graph_analyzer = EnhancedGraphAnalyzer()

class GraphInteractionRequest(BaseModel):
    interactions: list  # List of {from, to, type, weight}

class GraphNodeRequest(BaseModel):
    node_id: str

@app.post("/api/graph/build")
async def build_graph(request: GraphInteractionRequest):
    """Build/extend the social graph from interaction data."""
    global graph_analyzer
    
    if not request.interactions:
        raise HTTPException(status_code=400, detail="No interactions provided")
    
    graph_analyzer.bulk_add_interactions(request.interactions)
    
    return {
        "status": "graph_updated",
        "summary": graph_analyzer.get_graph_summary(),
        "interactions_added": len(request.interactions)
    }

@app.get("/api/graph/analyze")
async def analyze_graph():
    """Full graph analysis: centrality, brokers, suspicious clusters."""
    summary = graph_analyzer.get_graph_summary()
    
    if summary["total_nodes"] == 0:
        return {"error": "Graph is empty. Use /api/graph/build first."}
    
    return {
        "summary": summary,
        "high_centrality_nodes": graph_analyzer.identify_high_centrality_nodes(5),
        "brokers": graph_analyzer.identify_brokers(5),
        "suspicious_clusters": graph_analyzer.detect_suspicious_clusters()
    }

@app.get("/api/graph/brokers")
async def get_brokers():
    """Get broker/influencer nodes."""
    return {"brokers": graph_analyzer.identify_brokers(10)}

@app.get("/api/graph/suspicious")
async def get_suspicious_clusters():
    """Get suspicious bot-like clusters."""
    return {"clusters": graph_analyzer.detect_suspicious_clusters()}

@app.post("/api/graph/explain")
async def explain_node(request: GraphNodeRequest):
    """Get explanation for why a specific node matters."""
    return graph_analyzer.get_node_explanation(request.node_id)

@app.get("/api/graph/visualize")
async def export_visualization():
    """Export graph visualization as HTML (pyvis) or JSON."""
    output_path = graph_analyzer.export_visual_graph("graph_visualization.html")
    
    # Check if HTML or JSON was created
    if output_path.endswith(".json"):
        with open(output_path, "r") as f:
            import json
            data = json.load(f)
        return {"format": "json", "data": data}
    else:
        return {
            "format": "html",
            "path": output_path,
            "url": f"/static/{output_path}" if os.path.exists(output_path) else None
        }

@app.get("/api/graph/centrality")
async def get_centrality_metrics():
    """Get all centrality metrics for all nodes."""
    return {"metrics": graph_analyzer.compute_centrality_metrics()}

@app.delete("/api/graph/reset")
async def reset_graph():
    """Reset the graph to empty state."""
    global graph_analyzer
    graph_analyzer = EnhancedGraphAnalyzer()
    return {"status": "graph_reset"}


from .integrity.chain_of_custody import ChainOfCustody
from .integrity.hasher import TripleHasher

@app.get("/api/integrity/verify")
async def verify_chain_integrity():
    """Verify the entire chain of custody integrity."""
    try:
        coc = ChainOfCustody("SYSTEM_CHECK")
        is_valid = coc.verify_chain()
        
        # Count entries in ledger
        entry_count = 0
        if os.path.exists(coc.ledger_path):
            with open(coc.ledger_path, "r") as f:
                entry_count = len(f.readlines())
        
        return {
            "status": "VERIFIED" if is_valid else "COMPROMISED",
            "chain_valid": is_valid,
            "total_blocks": entry_count,
            "ledger_path": coc.ledger_path
        }
    except Exception as e:
        return {"status": "ERROR", "error": str(e)}

@app.get("/api/integrity/hashes/{filename}")
async def get_file_hashes(filename: str):
    """Calculate and return all hashes for a specific evidence file."""
    file_path = os.path.join(UPLOAD_DIR, filename)
    
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="File not found")
    
    try:
        hashes = TripleHasher.calculate_all_hashes(file_path)
        stat = os.stat(file_path)
        
        return {
            "filename": filename,
            "size_bytes": stat.st_size,
            "hashes": hashes,
            "algorithms": ["SHA3-512", "SHA-256", "BLAKE3"],
            "status": "COMPUTED"
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/api/integrity/ledger")
async def get_ledger_entries():
    """Get all chain of custody entries for display."""
    ledger_path = "custody_ledger.jsonl"
    entries = []
    
    if os.path.exists(ledger_path):
        import json
        with open(ledger_path, "r") as f:
            for line in f:
                try:
                    entry = json.loads(line)
                    entries.append({
                        "block_id": entry.get("block_id", "")[:8] + "...",
                        "action": entry.get("action"),
                        "timestamp": entry.get("timestamp"),
                        "actor": entry.get("actor"),
                        "prev_hash": entry.get("prev_hash", "")[:16] + "..."
                    })
                except:
                    pass
    
    return {"entries": entries, "total": len(entries)}

# === Confidence Scoring & Explainability APIs (PRD Extras) ===
from .core.confidence_scorer import ConfidenceScorer, ExplainabilityEngine
from .integrity.enhanced_report_gen import EnhancedReportGenerator

class ConfidenceInput(BaseModel):
    stylometry: dict = {}  # {authorship_match, radicalization_level, vocab_richness}
    graph: dict = {}  # {centrality_score, in_suspicious_cluster, connection_count}
    image: dict = {}  # {manipulation_score, ela_risk_level, ai_generated_prob}
    metadata: dict = {}  # {chain_verified, hash_match, timestamp_consistent}

@app.post("/api/confidence-score")
async def calculate_confidence_score(input: ConfidenceInput):
    """
    Calculate Attribution Confidence Score using PRD formula:
    0.35×Stylometry + 0.25×Graph + 0.20×Image + 0.20×Metadata
    """
    scorer = ConfidenceScorer()
    
    # Add stylometry score
    if input.stylometry:
        scorer.add_stylometry_score(
            input.stylometry.get("authorship_match", 50),
            input.stylometry.get("radicalization_level", "LOW"),
            input.stylometry.get("vocab_richness", 50)
        )
    
    # Add graph score
    if input.graph:
        scorer.add_graph_score(
            input.graph.get("centrality_score", 30),
            input.graph.get("in_suspicious_cluster", False),
            input.graph.get("connection_count", 5)
        )
    
    # Add image score
    if input.image:
        scorer.add_image_score(
            input.image.get("manipulation_score", 20),
            input.image.get("ela_risk_level", "LOW"),
            input.image.get("ai_generated_prob", 10)
        )
    
    # Add metadata score
    if input.metadata:
        scorer.add_metadata_score(
            input.metadata.get("chain_verified", True),
            input.metadata.get("hash_match", True),
            input.metadata.get("timestamp_consistent", True)
        )
    
    return scorer.calculate_composite_score()

@app.post("/api/explainability")
async def generate_explainability(input: ConfidenceInput):
    """Generate XAI explainability panel with transparent reasoning."""
    engine = ExplainabilityEngine()
    
    if input.stylometry:
        engine.explain_stylometry(
            input.stylometry.get("authorship_match", 0),
            input.stylometry.get("patterns", [])
        )
    
    if input.graph:
        engine.explain_graph(
            input.graph.get("centrality_score", 0),
            input.graph.get("cluster_status", "No cluster")
        )
    
    if input.image:
        engine.explain_image(
            input.image.get("manipulation_score", 0),
            input.image.get("ela_risk_level", "LOW")
        )
    
    if input.metadata:
        engine.explain_metadata(
            input.metadata.get("chain_status", "VERIFIED"),
            input.metadata.get("hash_count", 0)
        )
    
    return engine.generate_xai_panel()

class EnhancedReportRequest(BaseModel):
    case_id: str
    analysis_results: dict  # Combined results from all modules

@app.post("/api/report/enhanced")
async def generate_enhanced_report(request: EnhancedReportRequest):
    """Generate professional forensic intelligence report with all sections."""
    generator = EnhancedReportGenerator()
    
    output_path = f"Report_Enhanced_{request.case_id}.pdf"
    result = generator.generate_full_report(
        request.case_id,
        request.analysis_results,
        output_path
    )
    
    if result:
        return {
            "status": "generated",
            "path": output_path,
            "sections": [
                "Executive Summary",
                "Evidence Integrity",
                "Analysis Results",
                "Attribution Confidence Score",
                "Explainability Panel (XAI)",
                "Legal Disclaimer",
                "Cryptographic References"
            ]
        }
    else:
        raise HTTPException(status_code=500, detail="Report generation failed")

@app.get("/api/legal-disclaimer")
async def get_legal_disclaimer():
    """Get the ethical and legal disclaimer text."""
    return {
        "title": "ETHICAL & LEGAL DISCLAIMER",
        "disclaimer": """ARGUS is an investigative decision-support system, NOT an automated accusation engine.

• All findings require human expert review before action
• Results are probabilistic indicators, not definitive proof
• System operates offline-first with no live data scraping
• Designed for air-gapped forensic environments

This analysis is provided for investigative guidance only.
Final attribution decisions must be made by qualified human investigators with appropriate legal authority.""",
        "offline_design": {
            "claim": "Offline-First Design",
            "details": [
                "No live web scraping performed",
                "All analysis runs locally on provided data",
                "Compatible with air-gapped forensic environments",
                "Meets forensic chain-of-custody requirements"
            ]
        }
    }

# === GEOLOCATION EXTRACTION ENDPOINTS ===
from .vision.geo_extractor import GeoExtractor, FileRecoveryEngine

class GeotagRequest(BaseModel):
    file_path: str

@app.post("/api/vision/geotag")
async def extract_geotag(request: GeotagRequest):
    """Extract GPS coordinates and EXIF metadata from an image."""
    extractor = GeoExtractor()
    result = extractor.extract_geotag(request.file_path)
    return result

@app.post("/api/vision/geotag/upload")
async def extract_geotag_upload(file: UploadFile = File(...)):
    """Upload image and extract geotag data."""
    # Save temp file
    safe_filename = f"geo_{uuid.uuid4()}_{file.filename}"
    file_location = os.path.join(UPLOAD_DIR, safe_filename)
    
    with open(file_location, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)
    
    extractor = GeoExtractor()
    result = extractor.extract_geotag(file_location)
    result["uploaded_file"] = file_location
    return result

# === FILE RECOVERY / AUTOPSY ENDPOINTS ===
class RecoveryScanRequest(BaseModel):
    directory: str

@app.post("/api/forensics/scan")
async def scan_for_recovery(request: RecoveryScanRequest):
    """Scan directory for deleted/hidden files and suspicious content."""
    engine = FileRecoveryEngine()
    result = engine.scan_directory(request.directory)
    return result

@app.post("/api/forensics/scan-evidence")
async def scan_evidence_vault():
    """Scan the evidence vault for suspicious files."""
    engine = FileRecoveryEngine()
    result = engine.scan_directory(UPLOAD_DIR)
    return result

class FileAnalyzeRequest(BaseModel):
    file_path: str

@app.post("/api/forensics/analyze-file")
async def analyze_single_file(request: FileAnalyzeRequest):
    """Analyze a single file for forensic artifacts."""
    engine = FileRecoveryEngine()
    result = engine.analyze_file(request.file_path)
    return result

# === ENHANCED VISION ANALYSIS WITH GEOTAG ===
class FullVisionRequest(BaseModel):
    file_path: str
    include_geotag: bool = True
    include_manipulation: bool = True

@app.post("/api/vision/full-analysis")
async def full_vision_analysis(request: FullVisionRequest):
    """Complete vision analysis including ELA, manipulation, GAN, and geotag."""
    from .vision.ela_analyzer import ELAAnalyzer, ManipulationDetector
    from .vision.gan_detector import GANDetector
    
    result = {
        "file_path": request.file_path,
        "analyses": {}
    }
    
    # ELA Analysis
    ela = ELAAnalyzer()
    ela_result = ela.full_analysis(request.file_path, save_heatmap=True)
    result["analyses"]["ela"] = ela_result
    
    # Manipulation Detection
    if request.include_manipulation:
        detector = ManipulationDetector()
        manip_result = detector.detect(request.file_path)
        result["analyses"]["manipulation"] = manip_result.get("final_verdict", {})
    
    # GAN Detection
    gan = GANDetector()
    gan_result = gan.detect(request.file_path)
    result["analyses"]["gan"] = gan_result
    
    # Geotag Extraction
    if request.include_geotag:
        geo = GeoExtractor()
        geo_result = geo.extract_geotag(request.file_path)
        result["analyses"]["geotag"] = geo_result
    
    # Calculate overall authenticity score
    manip_score = result["analyses"].get("manipulation", {}).get("manipulation_score", 0)
    gan_prob = result["analyses"]["gan"].get("gan_probability", 0)
    
    overall_score = (manip_score + gan_prob) / 2
    result["overall_authenticity"] = {
        "score": round(100 - overall_score, 1),
        "verdict": "AUTHENTIC" if overall_score < 30 else "SUSPICIOUS" if overall_score < 60 else "LIKELY FAKE",
        "gan_probability": gan_prob,
        "manipulation_score": manip_score
    }
    
    return result

# === COMPLETE DASHBOARD DATA ENDPOINT ===
@app.get("/api/dashboard/summary")
async def get_dashboard_summary():
    """Get complete dashboard summary for frontend display."""
    # Count evidence files
    file_count = 0
    if os.path.exists(UPLOAD_DIR):
        file_count = len([f for f in os.listdir(UPLOAD_DIR) if os.path.isfile(os.path.join(UPLOAD_DIR, f))])
    
    return {
        "evidence_count": file_count,
        "integrity_status": "VERIFIED",
        "modules_active": 5,
        "system_status": "ONLINE",
        "capabilities": [
            {"name": "Evidence Integrity", "status": "active", "icon": "shield"},
            {"name": "NLP Stylometry", "status": "active", "icon": "file-text"},
            {"name": "Graph Analysis", "status": "active", "icon": "share-2"},
            {"name": "Visual Forensics", "status": "active", "icon": "scan"},
            {"name": "Report Generation", "status": "active", "icon": "file"}
        ]
    }

# === UNIFIED EVIDENCE PROCESSING PIPELINE ===
from .core.unified_pipeline import (
    UnifiedCaseState, EvidenceProcessor, 
    get_case_state, update_case_state, CASE_STORE
)

@app.post("/api/case/{case_id}/process-all")
async def process_all_evidence(case_id: str):
    """
    Process ALL evidence in the vault automatically.
    Runs: NLP, Image Analysis, Geotag, Graph Building, Scenario Generation, Attribution.
    """
    processor = EvidenceProcessor(case_id, UPLOAD_DIR)
    state = processor.process_all()
    
    return {
        "status": state.status,
        "case_id": case_id,
        "evidence_files": len(state.evidence_files),
        "entities_found": len(state.entities),
        "locations_found": len(state.locations),
        "scenarios_generated": len(state.scenarios),
        "images_analyzed": len(state.image_analyses),
        "texts_analyzed": len(state.text_analyses),
        "overall_risk_score": state.overall_risk_score,
        "final_attribution": state.final_attribution.suspect if state.final_attribution else None
    }

@app.get("/api/case/{case_id}/state")
async def get_full_case_state(case_id: str):
    """Get complete case state with all analysis results."""
    state = get_case_state(case_id)
    return state.to_dict()

@app.get("/api/case/{case_id}/entities")
async def get_case_entities(case_id: str):
    """Get all extracted entities for a case."""
    state = get_case_state(case_id)
    return {
        "entities": [
            {"name": e.name, "type": e.type, "source": e.source, "risk": e.risk_level}
            for e in state.entities
        ],
        "total": len(state.entities)
    }

@app.get("/api/case/{case_id}/scenarios")
async def get_case_scenarios(case_id: str):
    """Get generated scenarios linking entities to locations/times."""
    state = get_case_state(case_id)
    return {
        "scenarios": [
            {
                "entity": s.entity,
                "entity_type": s.entity_type,
                "location": s.location,
                "coordinates": s.coordinates,
                "timestamp": s.timestamp,
                "description": s.description,
                "risk_level": s.risk_level,
                "color": s.color,
                "evidence_source": s.evidence_source
            }
            for s in state.scenarios
        ],
        "total": len(state.scenarios)
    }

@app.get("/api/case/{case_id}/attribution")
async def get_final_attribution(case_id: str):
    """Get final attribution result with confidence score."""
    state = get_case_state(case_id)
    
    if not state.final_attribution:
        return {"status": "pending", "message": "Run /process-all first"}
    
    attr = state.final_attribution
    return {
        "status": "complete",
        "suspect": attr.suspect,
        "aliases": attr.aliases,
        "probable_location": attr.probable_location,
        "role": attr.role,
        "confidence_score": attr.confidence_score,
        "evidence_summary": attr.evidence_summary,
        "risk_breakdown": attr.risk_breakdown,
        "overall_risk_score": state.overall_risk_score
    }

@app.get("/api/case/{case_id}/images")
async def get_case_images(case_id: str):
    """Get all image analysis results for a case."""
    state = get_case_state(case_id)
    return {
        "images": [
            {
                "file_name": img.file_name,
                "file_path": img.file_path,
                "gan_probability": img.gan_probability,
                "ela_risk": img.ela_risk,
                "is_authentic": img.is_authentic,
                "geotag": {
                    "latitude": img.geotag.latitude,
                    "longitude": img.geotag.longitude,
                    "address": img.geotag.address,
                    "timestamp": img.geotag.timestamp,
                    "map_url": img.geotag.map_url
                } if img.geotag else None,
                "device_info": img.device_info,
                "warnings": img.warnings
            }
            for img in state.image_analyses
        ],
        "total": len(state.image_analyses)
    }

@app.get("/api/case/{case_id}/nlp-results")
async def get_case_nlp(case_id: str):
    """Get all NLP analysis results for a case."""
    state = get_case_state(case_id)
    return {
        "analyses": [
            {
                "source_file": t.source_file,
                "text_preview": t.text_preview[:200] + "..." if len(t.text_preview) > 200 else t.text_preview,
                "language": t.language,
                "entities": [{"name": e.name, "type": e.type} for e in t.entities],
                "threat_score": t.threat_score,
                "key_phrases": t.key_phrases[:10],
                "stylometry_match": t.stylometry_match,
                "stylometry_score": t.stylometry_score
            }
            for t in state.text_analyses
        ],
        "total": len(state.text_analyses)
    }

@app.get("/api/case/{case_id}/graph-data")
async def get_case_graph(case_id: str):
    """Get graph data for visualization."""
    state = get_case_state(case_id)
    return {
        "nodes": state.graph_nodes,
        "edges": state.graph_edges,
        "metrics": state.graph_metrics,
        "total_nodes": len(state.graph_nodes),
        "total_edges": len(state.graph_edges)
    }

@app.get("/api/case/{case_id}/locations")
async def get_case_locations(case_id: str):
    """Get all extracted locations for map visualization."""
    state = get_case_state(case_id)
    return {
        "locations": [
            {
                "address": loc.address,
                "latitude": loc.latitude,
                "longitude": loc.longitude,
                "timestamp": loc.timestamp,
                "source_file": loc.source_file,
                "map_url": loc.map_url
            }
            for loc in state.locations
        ],
        "total": len(state.locations)
    }

# === DEMO DATA LOADER ===
@app.post("/api/case/{case_id}/load-demo")
async def load_demo_case_data(case_id: str):
    """Load the sample case data for demonstration."""
    from .core.unified_pipeline import (
        EntityInfo, LocationData, ImageAnalysis, TextAnalysis, 
        Scenario, FinalAttribution, UnifiedCaseState
    )
    
    state = get_case_state(case_id)
    
    # Add demo entities (from user's case)
    demo_entities = [
        EntityInfo("Rohan Mehta", "PERSON", "case_file.pdf", "rohan_m24 victim from Pune", "LOW", "#22c55e"),
        EntityInfo("Ananya Iyer", "PERSON", "case_file.pdf", "ananya.codes victim from Bengaluru", "LOW", "#22c55e"),
        EntityInfo("Kunal Shah", "PERSON", "case_file.pdf", "kshah_fin victim from Ahmedabad", "LOW", "#22c55e"),
        EntityInfo("Neha Verma", "PERSON", "case_file.pdf", "neha_vx victim from Delhi", "LOW", "#22c55e"),
        EntityInfo("dev_arjun92", "PERSON", "stylometry_analysis", "Primary suspect identified via NLP", "HIGH", "#ef4444"),
        EntityInfo("dark._oracle", "ACCOUNT", "instagram_data", "Fake profile - Ethical Hacker claim", "HIGH", "#ef4444"),
        EntityInfo("truth_sentinel", "ACCOUNT", "twitter_data", "Fake profile - Whistleblower claim", "HIGH", "#ef4444"),
        EntityInfo("@zeroTrace", "ACCOUNT", "telegram_data", "Fake profile - Cyber Vigilante claim", "HIGH", "#ef4444"),
        EntityInfo("u/SignalBreaker", "ACCOUNT", "reddit_data", "Fake profile - Anonymous Insider", "HIGH", "#ef4444"),
    ]
    state.entities = demo_entities
    
    # Add demo location (from user's geotagged image)
    demo_location = LocationData(
        address="B4, Block A, Qutab Institutional Area, New Delhi, Delhi 110016",
        latitude=28.541449,
        longitude=77.182305,
        timestamp="18/09/24 01:02 PM GMT+05:30",
        source_file="IMG_2743.png",
        map_url="https://www.google.com/maps?q=28.541449,77.182305"
    )
    state.locations = [demo_location]
    
    # Add demo image analysis
    demo_image = ImageAnalysis(
        file_path="evidence_vault/IMG_2743.png",
        file_name="IMG_2743.png",
        gan_probability=12.5,
        ela_risk="LOW",
        is_authentic=True,
        geotag=demo_location,
        device_info={"make": "GPS Map Camera", "model": "Unknown"},
        warnings=[]
    )
    state.image_analyses = [demo_image]
    
    # Add demo NLP analysis
    demo_nlp = TextAnalysis(
        source_file="text_samples.txt",
        text_preview="Analyzed 152 text samples. Repeated phrases: 'mark my words', 'you were warned'. Common typos: definately, occurence",
        language="en",
        entities=demo_entities[:5],
        threat_score=78.0,
        stylometry_match="dev_arjun92",
        stylometry_score=92.4,
        key_phrases=["mark my words", "you were warned", "identity theft", "fake profile", "credential leak"]
    )
    state.text_analyses = [demo_nlp]
    
    # Add demo scenarios
    state.scenarios = [
        Scenario(
            entity="dev_arjun92",
            entity_type="SUSPECT",
            location="New Delhi, Qutab Institutional Area",
            coordinates=(28.541449, 77.182305),
            timestamp="18/09/24 01:02 PM",
            evidence_source="IMG_2743.png",
            description="SUSPECT dev_arjun92 linked to image captured at Qutab Institutional Area, New Delhi on Sep 18, 2024",
            risk_level="HIGH",
            color="#ef4444"
        ),
        Scenario(
            entity="Rohan Mehta",
            entity_type="VICTIM",
            location="Pune, Maharashtra",
            timestamp="Oct 2025",
            evidence_source="case_file.pdf",
            description="Victim Rohan Mehta from Pune - lost Instagram photos, Gmail password compromised",
            risk_level="LOW",
            color="#22c55e"
        ),
        Scenario(
            entity="Ananya Iyer",
            entity_type="VICTIM",
            location="Bengaluru, Karnataka",
            timestamp="Nov 2025",
            evidence_source="case_file.pdf",
            description="Victim Ananya Iyer from Bengaluru - LinkedIn profile image and GitHub bio stolen",
            risk_level="LOW",
            color="#22c55e"
        ),
        Scenario(
            entity="dark._oracle",
            entity_type="FAKE_PROFILE",
            location="Instagram",
            evidence_source="instagram_data",
            description="Fake Instagram profile claiming to be 'Ethical Hacker' - linked to bot network",
            risk_level="HIGH",
            color="#ef4444"
        ),
        Scenario(
            entity="9/13 images",
            entity_type="EVIDENCE",
            location="Digital",
            description="9 out of 13 profile images flagged as AI-generated (GAN artifacts detected)",
            risk_level="HIGH",
            color="#f59e0b"
        )
    ]
    
    # Add demo graph data
    state.graph_nodes = [
        {"id": "dev_arjun92", "label": "dev_arjun92", "type": "SUSPECT", "risk": "HIGH"},
        {"id": "dark._oracle", "label": "dark._oracle", "type": "FAKE", "risk": "HIGH"},
        {"id": "truth_sentinel", "label": "truth_sentinel", "type": "FAKE", "risk": "HIGH"},
        {"id": "@zeroTrace", "label": "@zeroTrace", "type": "FAKE", "risk": "HIGH"},
        {"id": "u/SignalBreaker", "label": "u/SignalBreaker", "type": "FAKE", "risk": "HIGH"},
        {"id": "rohan_m24", "label": "Rohan Mehta", "type": "VICTIM", "risk": "LOW"},
        {"id": "ananya.codes", "label": "Ananya Iyer", "type": "VICTIM", "risk": "LOW"},
        {"id": "kshah_fin", "label": "Kunal Shah", "type": "VICTIM", "risk": "LOW"},
        {"id": "neha_vx", "label": "Neha Verma", "type": "VICTIM", "risk": "LOW"},
        {"id": "bot_relay_1", "label": "Relay Bot 1", "type": "BOT", "risk": "MEDIUM"},
        {"id": "bot_relay_2", "label": "Relay Bot 2", "type": "BOT", "risk": "MEDIUM"},
        {"id": "bot_relay_3", "label": "Relay Bot 3", "type": "BOT", "risk": "MEDIUM"},
    ]
    
    state.graph_edges = [
        {"from": "dev_arjun92", "to": "dark._oracle", "type": "controls", "weight": 1.0},
        {"from": "dev_arjun92", "to": "truth_sentinel", "type": "controls", "weight": 1.0},
        {"from": "dev_arjun92", "to": "@zeroTrace", "type": "controls", "weight": 1.0},
        {"from": "dev_arjun92", "to": "u/SignalBreaker", "type": "controls", "weight": 1.0},
        {"from": "dark._oracle", "to": "rohan_m24", "type": "attacked", "weight": 0.8},
        {"from": "truth_sentinel", "to": "ananya.codes", "type": "attacked", "weight": 0.8},
        {"from": "@zeroTrace", "to": "kshah_fin", "type": "attacked", "weight": 0.8},
        {"from": "u/SignalBreaker", "to": "neha_vx", "type": "attacked", "weight": 0.8},
        {"from": "bot_relay_1", "to": "dev_arjun92", "type": "supports", "weight": 0.6},
        {"from": "bot_relay_2", "to": "dev_arjun92", "type": "supports", "weight": 0.6},
        {"from": "bot_relay_3", "to": "dev_arjun92", "type": "supports", "weight": 0.6},
        {"from": "bot_relay_1", "to": "bot_relay_2", "type": "coordinates", "weight": 0.5},
        {"from": "bot_relay_2", "to": "bot_relay_3", "type": "coordinates", "weight": 0.5},
    ]
    
    state.graph_metrics = {
        "total_nodes": 12,
        "total_edges": 13,
        "density": 0.197,
        "top_brokers": ["dev_arjun92"],
        "clusters": [
            {"id": 0, "members": ["dev_arjun92", "dark._oracle", "truth_sentinel", "@zeroTrace", "u/SignalBreaker"]},
            {"id": 1, "members": ["bot_relay_1", "bot_relay_2", "bot_relay_3"]},
            {"id": 2, "members": ["rohan_m24", "ananya.codes", "kshah_fin", "neha_vx"]}
        ]
    }
    
    # Final attribution
    state.final_attribution = FinalAttribution(
        suspect="dev_arjun92",
        aliases=["dark._oracle", "truth_sentinel", "@zeroTrace", "u/SignalBreaker"],
        probable_location="Hyderabad, Telangana",
        role="Network Originator / Broker",
        confidence_score=92.4,
        evidence_summary="Identified through Burrows' Delta stylometry (92.4% match), GraphSAGE centrality analysis, and cross-platform activity correlation",
        risk_breakdown={
            "nlp_score": 92.4,
            "graph_score": 85.0,
            "image_score": 69.2,  # 9/13 images AI-generated
            "location_score": 75.0
        }
    )
    
    state.overall_risk_score = 92.4
    state.status = "COMPLETED"
    
    update_case_state(case_id, state)
    
    return {
        "status": "demo_loaded",
        "case_id": case_id,
        "entities": len(state.entities),
        "scenarios": len(state.scenarios),
        "images": len(state.image_analyses),
        "locations": len(state.locations),
        "final_attribution": state.final_attribution.suspect,
        "confidence_score": state.final_attribution.confidence_score
    }

# === RESET / CLEAR CASE ===
@app.post("/api/case/{case_id}/reset")
async def reset_case(case_id: str):
    """
    Reset/clear a case state for fresh demo.
    Use this to demonstrate loading data fresh in front of audience.
    """
    from .core.unified_pipeline import UnifiedCaseState
    
    # Create fresh empty state
    fresh_state = UnifiedCaseState(case_id=case_id)
    fresh_state.status = "READY"
    
    update_case_state(case_id, fresh_state)
    
    # Also clear from localStorage hint
    return {
        "status": "reset",
        "case_id": case_id,
        "message": "Case cleared. Click 'Load Demo Case' to reload demo data."
    }

# === ENHANCED DEMO DATA WITH MULTIPLE GEOTAGGED IMAGES ===
@app.post("/api/case/{case_id}/load-demo-full")
async def load_full_demo_case(case_id: str):
    """
    Load enhanced demo with multiple geotagged images showing activity timeline.
    Best for judge demonstrations - shows progression of evidence.
    """
    from .core.unified_pipeline import (
        EntityInfo, LocationData, ImageAnalysis, TextAnalysis, 
        Scenario, FinalAttribution, UnifiedCaseState
    )
    
    state = get_case_state(case_id)
    
    # Demo entities
    demo_entities = [
        EntityInfo("Rohan Mehta", "PERSON", "case_file.pdf", "rohan_m24 victim from Pune", "LOW", "#22c55e"),
        EntityInfo("Ananya Iyer", "PERSON", "case_file.pdf", "ananya.codes victim from Bengaluru", "LOW", "#22c55e"),
        EntityInfo("Kunal Shah", "PERSON", "case_file.pdf", "kshah_fin victim from Ahmedabad", "LOW", "#22c55e"),
        EntityInfo("Neha Verma", "PERSON", "case_file.pdf", "neha_vx victim from Delhi", "LOW", "#22c55e"),
        EntityInfo("dev_arjun92", "PERSON", "stylometry_analysis", "Primary suspect identified via NLP", "HIGH", "#ef4444"),
        EntityInfo("dark._oracle", "ACCOUNT", "instagram_data", "Fake profile - Ethical Hacker claim", "HIGH", "#ef4444"),
        EntityInfo("truth_sentinel", "ACCOUNT", "twitter_data", "Fake profile - Whistleblower claim", "HIGH", "#ef4444"),
        EntityInfo("@zeroTrace", "ACCOUNT", "telegram_data", "Fake profile - Cyber Vigilante claim", "HIGH", "#ef4444"),
        EntityInfo("u/SignalBreaker", "ACCOUNT", "reddit_data", "Fake profile - Anonymous Insider", "HIGH", "#ef4444"),
    ]
    state.entities = demo_entities
    
    # MULTIPLE GEOTAGGED LOCATIONS - Activity Timeline
    location_1 = LocationData(
        address="B4, Block A, Qutab Institutional Area, New Delhi, Delhi 110016",
        latitude=28.541449,
        longitude=77.182305,
        timestamp="18/09/24 01:00 PM GMT+05:30",  # First sighting
        source_file="IMG_2744.jpg",
        map_url="https://www.google.com/maps?q=28.541449,77.182305"
    )
    
    location_2 = LocationData(
        address="B4, Block A, Qutab Institutional Area, New Delhi, Delhi 110016",
        latitude=28.541449,
        longitude=77.182305,
        timestamp="18/09/24 01:02 PM GMT+05:30",  # Second sighting (2 min later)
        source_file="IMG_2743.jpg",
        map_url="https://www.google.com/maps?q=28.541449,77.182305"
    )
    
    state.locations = [location_1, location_2]
    
    # Multiple image analyses
    image_1 = ImageAnalysis(
        file_path="evidence_vault/IMG_2744.jpg",
        file_name="IMG_2744.jpg",
        gan_probability=8.3,
        ela_risk="LOW",
        is_authentic=True,
        geotag=location_1,
        device_info={"make": "GPS Map Camera", "model": "Android Device"},
        warnings=[]
    )
    
    image_2 = ImageAnalysis(
        file_path="evidence_vault/IMG_2743.jpg",
        file_name="IMG_2743.jpg",
        gan_probability=12.5,
        ela_risk="LOW",
        is_authentic=True,
        geotag=location_2,
        device_info={"make": "GPS Map Camera", "model": "Android Device"},
        warnings=[]
    )
    
    state.image_analyses = [image_1, image_2]
    
    # NLP analysis
    demo_nlp = TextAnalysis(
        source_file="text_samples.txt",
        text_preview="Analyzed 152 text samples. Repeated phrases: 'mark my words', 'you were warned'. Common typos: definately, occurence",
        language="en",
        entities=demo_entities[:5],
        threat_score=78.0,
        stylometry_match="dev_arjun92",
        stylometry_score=92.4,
        key_phrases=["mark my words", "you were warned", "identity theft", "fake profile", "credential leak"]
    )
    state.text_analyses = [demo_nlp]
    
    # Enhanced scenarios with multiple images
    state.scenarios = [
        Scenario(
            entity="dev_arjun92",
            entity_type="SUSPECT",
            location="New Delhi, Qutab Institutional Area",
            coordinates=(28.541449, 77.182305),
            timestamp="18/09/24 01:00 PM",
            evidence_source="IMG_2744.jpg",
            description="SUSPECT dev_arjun92 FIRST SIGHTING at Qutab Institutional Area, New Delhi on Sep 18, 2024 at 01:00 PM",
            risk_level="HIGH",
            color="#ef4444"
        ),
        Scenario(
            entity="dev_arjun92",
            entity_type="SUSPECT",
            location="New Delhi, Qutab Institutional Area",
            coordinates=(28.541449, 77.182305),
            timestamp="18/09/24 01:02 PM",
            evidence_source="IMG_2743.jpg",
            description="SUSPECT dev_arjun92 SECOND SIGHTING at same location 2 minutes later - confirms presence",
            risk_level="HIGH",
            color="#ef4444"
        ),
        Scenario(
            entity="Rohan Mehta",
            entity_type="VICTIM",
            location="Pune, Maharashtra",
            timestamp="Oct 2025",
            evidence_source="case_file.pdf",
            description="Victim Rohan Mehta from Pune - lost Instagram photos, Gmail password compromised",
            risk_level="LOW",
            color="#22c55e"
        ),
        Scenario(
            entity="Ananya Iyer",
            entity_type="VICTIM",
            location="Bengaluru, Karnataka",
            timestamp="Nov 2025",
            evidence_source="case_file.pdf",
            description="Victim Ananya Iyer from Bengaluru - LinkedIn profile image and GitHub bio stolen",
            risk_level="LOW",
            color="#22c55e"
        ),
        Scenario(
            entity="dark._oracle",
            entity_type="FAKE_PROFILE",
            location="Instagram",
            evidence_source="instagram_data",
            description="Fake Instagram profile claiming to be 'Ethical Hacker' - linked to bot network controlled by dev_arjun92",
            risk_level="HIGH",
            color="#ef4444"
        ),
        Scenario(
            entity="9/13 profile images",
            entity_type="EVIDENCE",
            location="Digital Analysis",
            description="9 out of 13 profile images flagged as AI-generated (GAN artifacts detected) - indicates systematic fake profile creation",
            risk_level="HIGH",
            color="#f59e0b"
        ),
        Scenario(
            entity="Location Timeline",
            entity_type="ANALYSIS",
            location="New Delhi, India",
            timestamp="18/09/24 01:00-01:02 PM",
            description="Suspect photographed at SAME LOCATION across 2 images over 2-minute span - establishes physical presence with high confidence",
            risk_level="HIGH",
            color="#8b5cf6"
        )
    ]
    
    # Graph data
    state.graph_nodes = [
        {"id": "dev_arjun92", "label": "dev_arjun92", "type": "SUSPECT", "risk": "HIGH"},
        {"id": "dark._oracle", "label": "dark._oracle", "type": "FAKE", "risk": "HIGH"},
        {"id": "truth_sentinel", "label": "truth_sentinel", "type": "FAKE", "risk": "HIGH"},
        {"id": "@zeroTrace", "label": "@zeroTrace", "type": "FAKE", "risk": "HIGH"},
        {"id": "u/SignalBreaker", "label": "u/SignalBreaker", "type": "FAKE", "risk": "HIGH"},
        {"id": "rohan_m24", "label": "Rohan Mehta", "type": "VICTIM", "risk": "LOW"},
        {"id": "ananya.codes", "label": "Ananya Iyer", "type": "VICTIM", "risk": "LOW"},
        {"id": "kshah_fin", "label": "Kunal Shah", "type": "VICTIM", "risk": "LOW"},
        {"id": "neha_vx", "label": "Neha Verma", "type": "VICTIM", "risk": "LOW"},
        {"id": "bot_relay_1", "label": "Relay Bot 1", "type": "BOT", "risk": "MEDIUM"},
        {"id": "bot_relay_2", "label": "Relay Bot 2", "type": "BOT", "risk": "MEDIUM"},
        {"id": "bot_relay_3", "label": "Relay Bot 3", "type": "BOT", "risk": "MEDIUM"},
    ]
    
    state.graph_edges = [
        {"from": "dev_arjun92", "to": "dark._oracle", "type": "controls", "weight": 1.0},
        {"from": "dev_arjun92", "to": "truth_sentinel", "type": "controls", "weight": 1.0},
        {"from": "dev_arjun92", "to": "@zeroTrace", "type": "controls", "weight": 1.0},
        {"from": "dev_arjun92", "to": "u/SignalBreaker", "type": "controls", "weight": 1.0},
        {"from": "dark._oracle", "to": "rohan_m24", "type": "attacked", "weight": 0.8},
        {"from": "truth_sentinel", "to": "ananya.codes", "type": "attacked", "weight": 0.8},
        {"from": "@zeroTrace", "to": "kshah_fin", "type": "attacked", "weight": 0.8},
        {"from": "u/SignalBreaker", "to": "neha_vx", "type": "attacked", "weight": 0.8},
        {"from": "bot_relay_1", "to": "dev_arjun92", "type": "supports", "weight": 0.6},
        {"from": "bot_relay_2", "to": "dev_arjun92", "type": "supports", "weight": 0.6},
        {"from": "bot_relay_3", "to": "dev_arjun92", "type": "supports", "weight": 0.6},
        {"from": "bot_relay_1", "to": "bot_relay_2", "type": "coordinates", "weight": 0.5},
        {"from": "bot_relay_2", "to": "bot_relay_3", "type": "coordinates", "weight": 0.5},
    ]
    
    state.graph_metrics = {
        "total_nodes": 12,
        "total_edges": 13,
        "density": 0.197,
        "top_brokers": ["dev_arjun92"],
        "clusters": [
            {"id": 0, "members": ["dev_arjun92", "dark._oracle", "truth_sentinel", "@zeroTrace", "u/SignalBreaker"]},
            {"id": 1, "members": ["bot_relay_1", "bot_relay_2", "bot_relay_3"]},
            {"id": 2, "members": ["rohan_m24", "ananya.codes", "kshah_fin", "neha_vx"]}
        ]
    }
    
    # Final attribution
    state.final_attribution = FinalAttribution(
        suspect="dev_arjun92",
        aliases=["dark._oracle", "truth_sentinel", "@zeroTrace", "u/SignalBreaker"],
        probable_location="Hyderabad, Telangana",
        role="Network Originator / Broker",
        confidence_score=92.4,
        evidence_summary="Identified through Burrows' Delta stylometry (92.4% match), GraphSAGE centrality analysis, cross-platform activity correlation, AND physical presence confirmed via 2 geotagged images at same location within 2-minute span",
        risk_breakdown={
            "nlp_score": 92.4,
            "graph_score": 85.0,
            "image_score": 69.2,
            "location_score": 95.0  # Higher due to multiple location confirmations
        }
    )
    
    state.overall_risk_score = 92.4
    state.status = "COMPLETED"
    
    update_case_state(case_id, state)
    
    return {
        "status": "demo_loaded",
        "case_id": case_id,
        "entities": len(state.entities),
        "scenarios": len(state.scenarios),
        "images": len(state.image_analyses),
        "locations": len(state.locations),
        "geotagged_images": 2,
        "final_attribution": state.final_attribution.suspect,
        "confidence_score": state.final_attribution.confidence_score,
        "message": "Enhanced demo with multiple geotagged images loaded. Shows activity timeline."
    }

# === VOICE ASSISTANT API ===
from pydantic import BaseModel

class VoiceQueryRequest(BaseModel):
    query: str
    case_id: str

@app.post("/api/voice/query")
async def voice_query(request: VoiceQueryRequest):
    """
    Process a voice/text query and return a natural language response
    optimized for text-to-speech output.
    """
    from .voice.assistant import generate_voice_response, get_quick_response
    
    query = request.query
    case_id = request.case_id
    
    # Check for quick responses first
    quick = get_quick_response(query)
    if quick:
        return {"response": quick, "source": "quick"}
    
    # Get current case state
    try:
        state = get_case_state(case_id)
        case_data = state.to_dict()
    except:
        case_data = {}
    
    # Generate response using Gemini
    response = await generate_voice_response(query, case_data)
    
    return {
        "response": response,
        "source": "gemini",
        "case_id": case_id
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)

