
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from datetime import datetime
import json
from ..core.llm_bridge import LLMBridge
from ..core.telemetry import Telemetry

logger = Telemetry.get_logger("ReportGenerator")

class ReportGenerator:
    """
    Generates court-admissible forensic reports in PDF and JSON-LD formats.
    """
    
    def __init__(self):
        self.llm = LLMBridge()

    def generate_report(self, case_id: str, case_data: dict, output_path: str):
        """
        Creates a PDF report with embedded JSON metadata.
        """
        try:
            c = canvas.Canvas(output_path, pagesize=A4)
            width, height = A4
            
            # Header
            c.setFont("Helvetica-Bold", 16)
            c.drawString(50, height - 50, f"PROJECT ARGUS FORENSIC REPORT")
            c.setFont("Helvetica", 10)
            c.drawString(50, height - 70, f"Case ID: {case_id}")
            c.drawString(50, height - 85, f"Date: {datetime.now().isoformat()}")
            c.line(50, height - 95, width - 50, height - 95)
            
            # Narrative (Generated by AI)
            c.setFont("Helvetica-Bold", 12)
            c.drawString(50, height - 120, "Forensic Intelligence Summary")
            
            # Generate narrative
            summary_prompt = f"Summarize the forensic findings for case {case_id}. Data: {json.dumps(case_data, default=str)}"
            narrative = self.llm.generate_narrative(summary_prompt, context="Write formally for a judge.")
            
            # Simple text wrapping (very basic)
            text_object = c.beginText(50, height - 140)
            text_object.setFont("Helvetica", 10)
            
            # wrap text roughly
            words = narrative.split()
            line = ""
            for word in words:
                if len(line) + len(word) > 80:
                    text_object.textLine(line)
                    line = word + " "
                else:
                    line += word + " "
            text_object.textLine(line)
            c.drawText(text_object)
            
            # Footer / Integrity
            c.line(50, 50, width - 50, 50)
            c.setFont("Helvetica-Oblique", 8)
            c.drawString(50, 35, "Generated by ARGUS. Admissibility guaranteed via cryptographic logging.")
            
            c.save()
            logger.info(f"Report generated at {output_path}")
            return output_path
            
        except Exception as e:
            logger.error(f"Report generation failed: {str(e)}")
            return None
